feature/129 Request Review
KlubJagiellonski/pola-ios pull request #170
Opened 2020-12-17 22:23 UTC by jakub-kalamarz

2020-12-18 07:19 UTC, jakub-kalamarz commented
@WezSieTato Cześć! Mam trochę problem i nie wiem jak w prawidłowy sposób użyć swirtformat w projekcie, żeby przeszły testy. 

`$ swiftformat .` - poprawia mi 43 pliki razem z przesuwaniem `{` do następnej lini - może coś pomożesz ;)

2020-12-18 08:41 UTC, WezSieTato commented
`fastlane bundle exec format` i fastlane odpala [synx](https://github.com/venmo/synx) oraz swiftformat  :)

2020-12-18 08:59 UTC, jakub-kalamarz commented
To dlaczego pr nie przechodzi?

Wysłane z iPhone'a

> Wiadomość napisana przez Marcin Stepnowski <notifications@github.com> w dniu 18.12.2020, o godz. 09:41:
> 
> ﻿
> fastlane bundle exec format i fastlane odpala synx oraz swiftformat :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-18 09:35 UTC, WezSieTato commented
Musiał podbić się u Ciebie swiftformat. Nie masz zmian u siebie w Podfile.lock? Pody powinny zarządzać wersją swiftformat. Aktualnie korzystamy z domyślnych reguł i zmiana wersji powoduje zmianę formatowania. Odpaliłem u siebie formatowanie na tym PRze i zmieniły mi się tylko to co robiłeś. Załączam diffa:
[diff.txt](https://github.com/KlubJagiellonski/pola-ios/files/5714851/diff.txt)

2020-12-18 09:49 UTC, jakub-kalamarz commented
Dzięki, zerknę na to. Sorry, ze zawracam głowę. 

Wysłane z iPhone'a

> Wiadomość napisana przez Marcin Stepnowski <notifications@github.com> w dniu 18.12.2020, o godz. 10:36:
> 
> ﻿
> Musiał podbić się u Ciebie swiftformat. Nie masz zmian u siebie w Podfile.lock? Pody powinny zarządzać wersją swiftformat. Aktualnie korzystamy z domyślnych reguł i zmiana wersji powoduje zmianę formatowania. Odpaliłem u siebie formatowanie na tym PRze i zmieniły mi się tylko to co robiłeś. Załączam diffa:
> diff.txt
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-18 10:00 UTC, WezSieTato commented
Luzik. Jeśli pody się u Ciebie podbiły to znaczy, że trzymanie wersji tylko w Podfile.lock średnio się sprawdza i będzie trza dodać je też do Podfile. Ale to uwaga na przyszłość nie na ten PR.

2020-12-18 15:36 UTC, WezSieTato requested changes

2020-12-18 15:36 UTC, WezSieTato commented on BuyPolish/PolaUITests/PageObjects/ScanBarcodePage.swift
> +             return element.waitForExistence(timeout: 2)
Zamiast `2` użyj `waitForExistanceTimeout` jest to zmienna w `BasePage`. Dzięki temu wszystkie timeouty mają tą samą wielkość i w przypadku, gdy będzie potrzeba zmiany zrobi się to globalnie.

2020-12-19 09:45 UTC, WezSieTato approved these changes

2020-12-19 09:47 UTC, merged