Logi dla galerii
KlubJagiellonski/pola-ios pull request #234
Opened 2021-07-02 09:53 UTC by czater

Logi z dyskusji https://klubjagiellonski.slack.com/archives/CJYKV457W/p1625212216002200?thread_ts=1623917215.000300&cid=CJYKV457W

2021-07-02 10:04 UTC, WezSieTato requested changes

2021-07-02 10:04 UTC, WezSieTato commented on BuyPolish/Pola/Manager/Analytics/AnalyticsHelper.swift
> +        logEvent(name: .barcodeNotFound)
Zastanawiam się czy komunikat jest odpowiednio czytelny. Czy ktoś tego nie pomyli w przyszłości ze skanowaniem kodu. Przychodzi mi do głowy albo rozszerzenie nazwy o "barcodeNotFoundOnPhoto" lub dodanie tu parametru source jak przy już zeskanowanym produkcie.

2021-07-02 10:14 UTC, czater commented on BuyPolish/Pola/Manager/Analytics/AnalyticsHelper.swift
> +        logEvent(name: .barcodeNotFound)
Zrobione! 👍

2021-07-02 11:37 UTC, WezSieTato requested changes

2021-07-02 11:37 UTC, WezSieTato commented on BuyPolish/Pola/Manager/Analytics/AnalyticsHelper.swift
> +    func barcodeNotOnPhotoFoundDisplayed() {
Trochę yoda style Ci się zrobił w nazwie metody.

2021-07-02 11:37 UTC, WezSieTato commented on BuyPolish/Pola/Manager/Analytics/AnalyticsHelper.swift
> +    func openGallery() {
Brakuje testów do nowych metod.

2021-07-20 20:47 UTC, WezSieTato approved these changes

2021-07-20 20:47 UTC, merged